# Generated by Django 4.0.4 on 2022-12-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_coffee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
